// Code generated by http://www.gotool.top
package model

import (
	"time"
)

type User struct {
	Id          int64     `gorm:"column:id;primary_key;AUTO_INCREMENT;NOT NULL"`
	Uid         int64     `gorm:"column:uid;default:NULL"`
	Name        string    `gorm:"column:name;default:NULL"`
	Password    string    `gorm:"column:password;default:NULL"`
	Telephone   string    `gorm:"column:telephone;default:0"`
	CreatedTime time.Time `gorm:"column:created_time;default:NULL"`
	UpdatedTime time.Time `gorm:"column:updated_time;default:NULL"`
}

func (u *User) TableName() string {
	return "user"
}

type Books struct {
	Id          int64     `gorm:"column:id;primary_key;AUTO_INCREMENT;NOT NULL"`
	Title       string    `gorm:"column:title;default:NULL"`
	Num         int32     `gorm:"column:num;NOT NULL"`
	CreatedTime time.Time `gorm:"column:created_time;default:NULL"`
	UpdatedTime time.Time `gorm:"column:updated_time;default:NULL"`
}

func (b *Books) TableName() string {
	return "books"
}

type UserBooks struct {
	Id          int64     `gorm:"column:id;primary_key;AUTO_INCREMENT;NOT NULL"`
	UserId      int64     `gorm:"column:user_id;NOT NULL"`
	UserName    string    `gorm:"column:user_name;default:NULL"`
	BooksTitle  string    `gorm:"column:books_title;default:NULL"`
	Status      int64     `gorm:"column:status;NOT NULL"`
	CreatedTime time.Time `gorm:"column:created_time;default:NULL"`
	UpdatedTime time.Time `gorm:"column:updated_time;default:NULL"`
}

func (u *UserBooks) TableName() string {
	return "user_books"
}
